# Generated by Django 5.2.10 on 2026-01-29 21:02

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='', image_field=None, max_length=7, samples=None, verbose_name='color'),
        ),
    ]
