# Generated by Django 5.2.10 on 2026-01-29 21:22

from django.db import migrations

def create_default_categories(apps, schema_editor):
    Category = apps.get_model('taskapp', 'CategoryModel')
    categories = [
        {'name': 'Trabajo', 'description': 'Trabajo'},
        {'name': 'Estudio', 'description': 'Estudio'},
        {'name': 'Casa', 'description': 'Casa'},
        {'name': 'Familia', 'description': 'Familia'},
        {'name': 'Diversión', 'description': 'Diversión'},
    ]
    for item in categories:
        Category.objects.get_or_create(**item)

class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0002_alter_taskmodel_color'),
    ]

    operations = [
        migrations.RunPython(create_default_categories),
    ]
